# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-09 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Action', 'verbose_name_plural': 'Actions'},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='difficult_aspects_text',
            new_name='difficult_aspects',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='overcome_difficult_aspects_text',
            new_name='overcome_difficult_aspects',
        ),
    ]
