# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-10 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0002_auto_20190609_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='goal',
        ),
        migrations.RenameField(
            model_name='intention',
            old_name='intention',
            new_name='intention_text',
        ),
        migrations.AlterField(
            model_name='review',
            name='enjoyable_aspects',
            field=models.TextField(blank=True, help_text=b'What was enjoyable about working towards this goal?', verbose_name='Enjoyable Aspects'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_period_end_date',
            field=models.DateField(blank=True, verbose_name='Review Period End'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_period_start_date',
            field=models.DateField(blank=True, verbose_name='Review Period Start'),
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
