# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-11 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0003_auto_20190610_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='title',
        ),
        migrations.AddField(
            model_name='goal',
            name='stative_verb',
            field=models.CharField(default='Have', help_text=b'A Stative Verb which expresses the end state of the goal, ie: have, be, know, like', max_length=300, verbose_name='Stative Verb'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(default='1 million pounds', help_text=b'A Predicate Noun which expresses the status of the goal', max_length=500, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
