# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-11 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0004_auto_20190611_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='action_name',
        ),
        migrations.AddField(
            model_name='action',
            name='action_verb',
            field=models.CharField(choices=[(b'Increase', b'Increase'), (b'Reduce', b'Reduce'), (b'Maintain', b'Maintain')], default=b'Increase', help_text=b'What action is this?', max_length=100, verbose_name='Action Verb'),
        ),
        migrations.AddField(
            model_name='action',
            name='activity',
            field=models.CharField(default='calorie intake', help_text=b'This should be the activity which moves you towards the goal, expressed as a nominalisation, eg calorie intake', max_length=300, verbose_name='Activity'),
            preserve_default=False,
        ),
    ]
