# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-17 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0005_auto_20190611_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='parent_goal',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='subgoals', to='achievement.Goal', verbose_name='Parent Goal'),
            preserve_default=False,
        ),
    ]
