# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-17 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0008_auto_20200517_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='parent_goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgoals', to='achievement.Goal', verbose_name='Parent Goal'),
        ),
    ]
