# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-17 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0009_auto_20200517_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='importance',
            field=models.FloatField(null=True, verbose_name=b'Importance'),
        ),
        migrations.AddField(
            model_name='goal',
            name='urgency',
            field=models.FloatField(null=True, verbose_name=b'Urgency'),
        ),
    ]
