# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-21 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0011_auto_20200517_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name': 'Goal', 'verbose_name_plural': 'Goals'},
        ),
        migrations.AddField(
            model_name='goal',
            name='position',
            field=models.IntegerField(default=1, null=True, verbose_name='Position'),
        ),
    ]
